block_cipher = None


a = Analysis(['gui.py'],
             binaries=[],
             datas=[('message.mp3', 'sound'), ('connect.mp3','sound'), ('icon.ico','.'), 
("Visuals/Backgrounds/Metal.png", "Visuals/Backgrounds"),
("Visuals/Backgrounds/Paper.png", "Visuals/Backgrounds"),
("Visuals/Backgrounds/Wood.png", "Visuals/Backgrounds"),
("Visuals/Borders/Bottom.png", "Visuals/Borders"),
("Visuals/Borders/BottomLeft.png", "Visuals/Borders"),
("Visuals/Borders/BottomLeftRight.png", "Visuals/Borders"),
("Visuals/Borders/BottomLeftTop.png", "Visuals/Borders"),
("Visuals/Borders/BottomRight.png", "Visuals/Borders"),
("Visuals/Borders/BottomRightLeft.png", "Visuals/Borders"),
("Visuals/Borders/BottomRightTop.png", "Visuals/Borders"),
("Visuals/Borders/Left.png", "Visuals/Borders"),
("Visuals/Borders/Right.png", "Visuals/Borders"),
("Visuals/Borders/Top.png", "Visuals/Borders"),
("Visuals/Borders/TopLeft.png", "Visuals/Borders"),
("Visuals/Borders/TopLeftBottom.png", "Visuals/Borders"),
("Visuals/Borders/TopLeftRight.png", "Visuals/Borders"),
("Visuals/Borders/TopRight.png", "Visuals/Borders"),
("Visuals/Borders/TopRightBottom.png", "Visuals/Borders"),
("Visuals/Buttons/CloseActive.png", "Visuals/Buttons"),
("Visuals/Buttons/CloseClicked.png", "Visuals/Buttons"),
("Visuals/Buttons/CloseNormal.png", "Visuals/Buttons"),
("Visuals/CheckBox/RoundActive.png", "Visuals/CheckBox"),
("Visuals/CheckBox/RoundDisabled.png", "Visuals/CheckBox"),
("Visuals/CheckBox/RoundNormal.png", "Visuals/CheckBox"),
("Visuals/Cursor/AoE.png", "Visuals/Cursor"),
("Visuals/Fonts/MTCORSVA.TTF", "Visuals/Fonts"),
("Visuals/Fonts/formal-436-bt-5947cc2c8b950.ttf", "Visuals/Fonts"),
("Visuals/TextBlock/TextBlock.png", "Visuals/TextBlock"),
],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter','matplotlib'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='ESO Packet Tracker',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          runtime_tmpdir=None,
          console=False,
icon='icon.ico',
version='file_version_info.txt' )