en = {
    "language": "en",
    "country": "name_en",
    "playerleftchat": "Player {un} left the chat {cn}",
    "youleftchat": 'You left the chat "{n}"',
    "playerwritechat": '{un} writes to chat "{cn}": {m}',
    "youwritechat": 'You write to chat "{cn}": {m}',
    "updatedchatlist": "You updated the chat list.",
    "playerjoinchat": 'Player {un} joined the chat "{cn}"',
    "youjoinchat": 'You joined the chat "{n}"',
    "playerinvite": 'Player {un} invited you to the lobby "{n}": map {s10}, players({playerstr})',
    "lobbyupdated": 'Lobby "{n}" updated: map {s10}, players({playerstr})',
    "playerremoved": "Player {n} was removed",
    "createlobby": "You created a lobby",
    "youleftlobby": "You left the lobby",
    "playerconncet": "Player {n} is connecting: {IP}, {country}",
    "playerconnectvoice": "Player {n} from {country} is connecting",
    "startqs": "You started QuickSeatch",
    "youinvite": "You invited {iu} to the lobby",
    "cancelqs": "You canceled QuickSerach",
    "fflremove": "You removed player {name} from friends/foes list",
    "fradded": "You added player {n} to friends list",
    "fadded": "You added player {n} to foes list",
    "frmoved": "You moved player {name} to friends list",
    "fmoved": "You moved player {name} to foes list",
    "stat": "Player stat {un}\n",
    "regdate": "Registration date: {cd}\n",
    "lastactive": "Last active: {lld}\n",
    "clan": "Clan {ca} - {cn}\n",
    "supremacy": "Supremacy: games {sg}, wins {sw}, winrate {sp}%, PR {spts} \n",
    "treaty": "Treaty: games {tg}, wins {tw}, winrate {tp}%, PR {tpts} \n",
    "dm": "Deathmatch: games {dg}, wins {dw}, winrate {dp}%, PR {dpts}",
    "playerwhisper": "Player {n} whispers : {w}",
    "playerwhispervoice": "Player {n} whispers",
    "youwhisper": "You whisper to {name} : {whisper}",
    "listlobbyupdate": "You updated list of lobbies",
    "eso": "Players on ESO: {num}",
    "qsupdated": "QuickSearch updated: {ut}",
    "friendleft": "Friend {n} left ESO",
    "Vanilla": "Vanilla",
    "tad": "The Asian Dynasties",
    "friendingame": "Friend {n} started game in {gt}",
    "friendonline": "Friend {n} is online in {gt}",
    "yousay": "You write to {dst}: {text}",
    "yousaytaunt": "You say taunt to {dst}: {text}",
    "playersay": "Player {src} writes: {text}",
    "playersaytaunt": "Player {src} says taunt: {text}",
    "plogs": "ESO Packets log",
    "playersinlobby": "Players in lobby",
    "ipandeso": "IP and names database",
    "filter": "Filter:",
    "black": "Black (unformatted messages)",
    "violet": "Violet (ESO actions - population, statistics)",
    "blue": "Blue (your actions)",
    "green": "Greens (interaction of other players with you)",
    "red": "Red (error messages)",
    "sounds": "Sounds",
    "connection": "Voice player's connections",
    "Friends": "Voice friends activity",
    "Messages": "Voice messages",
    "Notifications": "Notifications sounds",
    "unknown": "unknown",
    "tips": "Right click on the item with the IP address will geolocate, and left click will apply the filter.",
    "Colors": "Log filter",
    "settings": "Settings",
    "RecordedGame": "Records Parser",
    "GameInfo": "Game Info",
    "Decks": "Decks",
    "GameActions": "Game Actions",
    "openfile": "Open",
    "openlabel": "Open Recorded Game file: ",
    "parsingwarning": "Parsing was failed!",
    "Version": "Version: ",
    "Mode": "Mode: ",
    "min.": " min.",
    "Duration": "Duration: ",
    "apm": "Actions per minute: ",
    "resigned": "resigned",
    "spawn_unit": "spawn unit: ",
    "shipment": "shipment: ",
    "build": "build: ",
    "pick_deck": "pick deck: ",
    "research_tech1": "research tech: ",
    "research_tech2": "cheat tech: ",
    "research_tech3": "cheat tech: ",
    "train": "train: ",

    "cbresigned": "Resigned",
    "cbspawn_unit": "Spawn unit",
    "cbshipment": "Shipment",
    "cbbuild": "Build",
    "cbpick_deck": "Pick deck",
    "cbresearch_tech1": "Research tech",
    "cbresearch_tech23": "Cheat tech",
    "cbtrain": "Train",
    "playerscolors": "Players Colors:",
    "playersaction": "Players Actions:",
    "ISP": "ISP: ",
    "timezone":"Timezone: ",
    "IP Address":"IP Address",
    "ESO Name": "ESO Name"
}

ru = {
    "language": "ru",
    "country": "name_ru",
    "playerleftchat": "Игрок {un} покинул чат {cn}",
    "youleftchat": 'Вы покинули чат "{n}"',
    "playerwritechat": '{un} пишет в чат "{cn}": {m}',
    "youwritechat": 'Вы пишите в чат "{cn}": {m}',
    "updatedchatlist": "Вы обновили список чатов.",
    "playerjoinchat": 'Игрок {un} зашел в чат "{cn}"',
    "youjoinchat": 'Вы зашли в чат "{n}"',
    "playerinvite": 'Игрок {un} пригласил вас в комнату "{n}": карта {s10}, игроки({playerstr})',
    "lobbyupdated": 'Комната "{n}" обновлена: карта {s10}, игроки({playerstr})',
    "playerremoved": "Игрок {n} вышел",
    "createlobby": "Вы создали комнату",
    "youleftlobby": "Вы покинули комнату",
    "playerconncet": "Игрок {n} присоединяется: {IP}, {country}",
    "playerconnectvoice": "Игрок {n} из {country} присоединяется",
    "startqs": "Вы запустили быстрый поиск",
    "youinvite": "Вы пригласили {iu} в комнату",
    "cancelqs": "Вы отменили быстрый поиск",
    "fflremove": "Вы удалили игрока {name} из списка друзей/черного списка",
    "fradded": "Вы добавили игрока {n} в список друзей",
    "fadded": "Вы добавили игрока {n} в черный список",
    "frmoved": "Вы переместили игрока {name} в список друзей",
    "fmoved": "Вы переместили игрока {name} в черный список",
    "stat": "Статистика игрока {un}\n",
    "regdate": "Дата регистрации: {cd}\n",
    "lastactive": "Последняя активность: {lld}\n",
    "clan": "Клан {ca} - {cn}\n",
    "supremacy": "Supremacy: игры {sg}, победы {sw}, винрейт {sp}%, PR {spts} \n",
    "treaty": "Treaty: игры {tg}, победы {tw}, винрейт {tp}%, PR {tpts} \n",
    "dm": "Deathmatch: игры {dg}, победы {dw}, винрейт {dp}%, PR {dpts}",
    "playerwhisper": "Игрок {n} пишет : {w}",
    "playerwhispervoice": "Игрок {n} пишет",
    "youwhisper": "Вы шепчете {name} : {whisper}",
    "listlobbyupdate": "Вы обновили список комнат",
    "eso": "Игроков на ESO: {num}",
    "qsupdated": "Быстрый поиск обновлен: {ut}",
    "friendleft": "Друг {n} покинул ESO",
    "Vanilla": "Ванилле",
    "tad": "Династиях",
    "friendingame": "Друг {n} начал игру в {gt}",
    "friendonline": "Друг {n} в сети в {gt}",
    "yousay": "Вы пишите {dst}: {text}",
    "yousaytaunt": "Вы произносите фразу для {dst}: {text}",
    "playersay": "Игрок {src} пишет: {text}",
    "playersaytaunt": "Игрок {src} произносит фразу: {text}",
    "plogs": "Лог пакетов ESO",
    "playersinlobby": "Игроки в лобби",
    "ipandeso": "База данных IP и имен",
    "filter": "Фильтр:",
    "black": "Черные (неотформатированные сообщения)",
    "violet": "Фиолетовые (действия ESO - популяция, статистика)",
    "blue": "Синие (ваши действия)",
    "green": "Зеленые (взаимодействие других игроков с вами)",
    "red": "Красные (сообщения об ошибках)",
    "sounds": "Звуки",
    "connection": "Озвучка присоединения игроков",
    "Friends": "Озвучка активности друзей",
    "Messages": "Озвучка сообщений",
    "Notifications": "Звук уведомлений",
    "unknown": "неизвестно",
    "tips": "Правый клик мыши по строке с IP адресом выполнит геолокацию, а левый клик применит фильтр.",
    "Colors": "Фильтр логов",
    "settings": "Настройки",
    "RecordedGame": "Сканер записей",
    "GameInfo": "Данные игры",
    "Decks": "Деки",
    "GameActions": "Действия",
    "openfile": "Открыть",
    "openlabel": "Выберите файл записи: ",
    "parsingwarning": "При обработке записи возникли ошибки!",
    "Version": "Версия: ",
    "Mode": "Режим: ",
    "min.": " мин.",
    "Duration": "Длительность: ",
    "apm": "Действий в минуту: ",
    "resigned": "сдался",
    "spawn_unit": "спавнит: ",
    "shipment": "поставка: ",
    "build": "строит: ",
    "pick_deck": "выбирает деку: ",
    "research_tech1": "улучшение: ",
    "research_tech2": "чит-улучшение: ",
    "research_tech3": "чит-улучшение: ",
    "train": "тренирует: ",
    "IP Address":"IP адрес",
    "ESO Name": "Имя в ESO",

    "cbresigned": "Сдался",
    "cbspawn_unit": "Спавн юнитов",
    "cbshipment": "Поставки",
    "cbbuild": "Строительство",
    "cbpick_deck": "Выбор деки",
    "cbresearch_tech1": "Улучшения",
    "cbresearch_tech23": "Чит-улучшения",
    "cbtrain": "Тренировка",
    "playerscolors": "Цвета игроков:",
    "playersaction": "Действия игроков:",
    "ISP": "Провайдер: ",
    "timezone":"Часовой пояс: ",
}
