en = {
    "language": "en",
    "country": "name_en",
    "playerleftchat": "Player {un} left the chat {cn}",
    "youleftchat": 'You left the chat "{n}"',
    "playerwritechat": '{un} writes to chat "{cn}": {m}',
    "youwritechat": 'You write to chat "{cn}": {m}',
    "updatedchatlist": "You updated the chat list.",
    "playerjoinchat": 'Player {un} joined the chat "{cn}"',
    "youjoinchat": 'You joined the chat "{n}"',
    "playerinvite": 'Player {un} invited you to the lobby "{n}": map {s10}, players({playerstr})',
    "lobbyupdated": 'Lobby "{n}" updated: map {s10}, players({playerstr})',
    "playerremoved": "Player {n} was removed",
    "createlobby": "You created a lobby",
    "youleftlobby": "You left the lobby",
    "playerconncet": "Player {n} is connecting: {IP}, {country}",
    "playerconnectvoice": "Player {n} from {country} is connecting",
    "startqs": "You started QuickSeatch",
    "youinvite": "You invited {iu} to the lobby",
    "cancelqs": "You canceled QuickSerach",
    "fflremove": "You removed player {name} from friends/foes list",
    "fradded": "You added player {n} to friends list",
    "fadded": "You added player {n} to foes list",
    "frmoved": "You moved player {name} to friends list",
    "fmoved": "You moved player {name} to foes list",
    "stat": "Player stat {un}\n",
    "regdate": "Registration date: {cd}\n",
    "lastactive": "Last active: {lld}\n",
    "clan": "Clan {ca} - {cn}\n",
    "supremacy": "Supremacy: games {sg}, wins {sw}, winrate {sp}%, PR {spts} \n",
    "treaty": "Treaty: games {tg}, wins {tw}, winrate {tp}%, PR {tpts} \n",
    "dm": "Deathmatch: games {dg}, wins {dw}, winrate {dp}%, PR {dpts} \n",
    "playerwhisper": "Player {n} whispers : {w}",
    "playerwhispervoice": "Player {n} whispers",
    "youwhisper": "You whisper to {name} : {whisper}",
    "listlobbyupdate": "You updated list of lobbies",
    "eso": "Players on ESO: {num}",
    "qsupdated": "QuickSearch updated: {ut}",
    "friendleft": "Friend {n} left ESO",
    "Vanilla": "Vanilla",
    "tad": "The Asian Dynasties",
    "friendingame": "Friend {n} started game in {gt}",
    "friendonline": "Friend {n} is online in {gt}",
    "yousay":"You write to {dst}: {text}",
    "yousaytaunt":"You say taunt to {dst}: {text}",
    "playersay":"Player {src} writes: {text}",
    "playersaytaunt":"Player {src} says taunt: {text}",
}

ru = {
    "language": "ru",
    "country": "name_ru",
    "playerleftchat": "Игрок {un} покинул чат {cn}",
    "youleftchat": 'Вы покинули чат "{n}"',
    "playerwritechat": '{un} пишет в чат "{cn}": {m}',
    "youwritechat": 'Вы пишите в чат "{cn}": {m}',
    "updatedchatlist": "Вы обновили список чатов.",
    "playerjoinchat": 'Игрок {un} зашел в чат "{cn}"',
    "youjoinchat": 'Вы зашли в чат "{n}"',
    "playerinvite": 'Игрок {un} пригласил вас в комнату "{n}": карта {s10}, игроки({playerstr})',
    "lobbyupdated": 'Комната "{n}" обновлена: карта {s10}, игроки({playerstr})',
    "playerremoved": "Игрок {n} вышел",
    "createlobby": "Вы создали комнату",
    "youleftlobby": "Вы покинули комнату",
    "playerconncet": "Игрок {n} присоединяется: {IP}, {country}",
    "playerconnectvoice": "Игрок {n} из {country} присоединяется",
    "startqs": "Вы запустили быстрый поиск",
    "youinvite": "Вы пригласили {iu} в комнату",
    "cancelqs": "Вы отменили быстрый поиск",
    "fflremove": "Вы удалили игрока {name} из списка друзей/черного списка",
    "fradded": "Вы добавили игрока {n} в список друзей",
    "fadded": "Вы добавили игрока {n} в черный список",
    "frmoved": "Вы переместили игрока {name} в список друзей",
    "fmoved": "Вы переместили игрока {name} в черный список",
    "stat": "Статистика игрока {un}\n",
    "regdate": "Дата регистрации: {cd}\n",
    "lastactive": "Последняя активность: {lld}\n",
    "clan": "Клан {ca} - {cn}\n",
    "supremacy": "Supremacy: игры {sg}, победы {sw}, винрейт {sp}%, PR {spts} \n",
    "treaty": "Treaty: игры {tg}, победы {tw}, винрейт {tp}%, PR {tpts} \n",
    "dm": "Deathmatch: игры {dg}, победы {dw}, винрейт {dp}%, PR {dpts} \n",
    "playerwhisper": "Игрок {n} шепчет : {w}",
    "playerwhispervoice": "Игрок {n} шепчет",
    "youwhisper": "Вы шепчете {name} : {whisper}",
    "listlobbyupdate": "Вы обновили список комнат",
    "eso": "Игроков на ESO: {num}",
    "qsupdated": "Быстрый поиск обновлен: {ut}",
    "friendleft": "Друг {n} покинул ESO",
    "Vanilla": "Ванилле",
    "tad": "Династиях",
    "friendingame": "Друг {n} начал игру в {gt}",
    "friendonline": "Друг {n} в сети в {gt}",
    "yousay":"Вы пишите {dst}: {text}",
    "yousaytaunt":"Вы произносите насмешку для {dst}: {text}",
    "playersay":"Игрок {src} пишет: {text}",
    "playersaytaunt":"Игрок {src} произносит насмешку: {text}",
}
